import React,{useState,useRef} from 'react';
import {Link} from 'react-router-dom';
import {Layout,Intro,Button} from 'components/Website/Layout.jsx';
import {formats,buildPlan,campaignLink,planEnquiry} from './plan';
const initial={expertise:'',customer:'',problem:'',format:'review',hours:'5–10'};
export default function OpcPage({location}){
 const params=new URLSearchParams(location.search),[lang,setLang]=useState(params.get('lang')==='zh'?'zh':'en'),[data,setData]=useState(initial),[plan,setPlan]=useState(null),[draft,setDraft]=useState(''),[status,setStatus]=useState(''); const result=useRef(null),form=useRef(null); const zh=lang==='zh',source=['xiaohongshu','twitter','linkedin'].includes(params.get('source'))?params.get('source'):'website';
 React.useEffect(()=>{setLang(new URLSearchParams(location.search).get('lang')==='zh'?'zh':'en');setStatus('');},[location.search]);
 const t=(en,cn)=>zh?cn:en;
 const update=e=>{setData({...data,[e.target.name]:e.target.value});};
 const start=()=>{form.current.scrollIntoView({block:'start',behavior:'smooth'});form.current.querySelector('input').focus({preventScroll:true});};
 const generate=e=>{e.preventDefault();try{const p=buildPlan(data,lang);setPlan(p);setDraft(p.text);setStatus('');}catch(error){setStatus(t('Please complete each answer with meaningful text.','请填写每一项，输入不能只包含空格。'));}};
 React.useEffect(()=>{if(plan&&result.current){result.current.scrollIntoView({block:'start',behavior:'smooth'});result.current.focus({preventScroll:true});}},[plan]);
 const copy=async(text,message)=>{try{await navigator.clipboard.writeText(text);setStatus(message);}catch(e){setStatus(t('Copy is unavailable in this browser. Select and copy the text manually.','此浏览器无法自动复制，请选中文本手动复制。'));}};
 const example=()=>{setData(zh?{expertise:'工作流程梳理与 AI 自动化',customer:'澳洲小型服务企业',problem:'客户咨询和跟进占用太多时间',format:'setup',hours:'5–10'}:{expertise:'workflow design and AI automation',customer:'small Australian service businesses',problem:'too much time spent handling enquiries and follow-ups',format:'setup',hours:'5–10'});setStatus('');};
 const download=()=>{const url=URL.createObjectURL(new Blob([draft],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='NextGenius-OPC-Service-Plan.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus(t('Your text file has been downloaded.','文本文件已下载。'));};
 return <Layout title={t('Build Your First OPC Service','打造你的第一个 OPC 服务')} description={t('Turn your expertise into a clear service offer. Create a free, editable OPC service plan with NextGenius. No signup required.','把你的专业能力变成可出售的服务。免费生成可编辑的 OPC 服务方案，无需注册。')} path="/opc"><div className="ng-opc" lang={zh?'zh-CN':'en'}><section className="ng-hero"><div className="ng-wrap"><div className="opc-top"><span className="ng-eyebrow">NEXTGENIUS · AUSTRALIA OPC</span><div className="opc-language" aria-label="Language"><button onClick={()=>setLang('en')} aria-pressed={!zh}>English</button><button onClick={()=>setLang('zh')} aria-pressed={zh}>中文</button></div></div><div className="ng-hero-grid"><div><h1>{t('You have the skills.','你有专业能力。')}<br/><em>{t('Let’s shape your service.','让它成为一门服务。')}</em></h1><p>{t('Turn what you know into something a customer can understand, buy and use. Start with a clear offer, a manageable scope and a practical first step.','把你会的东西，变成客户看得懂、愿意买、能交付的服务。从明确客户、梳理套餐，到迈出第一步。')}</p><div className="ng-actions"><button className="ng-button" onClick={start}>{t('Create my free service plan ↗','免费生成我的服务方案 ↗')}</button></div><div className="ng-hero-note">{t('5 questions · No signup · Editable result','5 个问题 · 无需注册 · 结果可编辑')}</div></div><aside className="ng-workflow"><span className="ng-eyebrow">{t('LEAVE WITH A USEFUL FIRST DRAFT','带走一份可以开始行动的草稿')}</span>{[[t('A focused offer','明确的服务定位'),t('Who you help and the problem you solve.','你帮助谁，解决什么问题。')],[t('A delivery & pricing outline','交付与报价框架'),t('Scope, steps and a pricing model to validate.','服务范围、交付步骤与待验证的报价结构。')],[t('Your first-week checklist','第一周行动清单'),t('Customer conversations, a sample and a pilot.','客户访谈、示例成果与小范围试单。')]].map(([h,p],i)=><div key={h}><span>0{i+1}</span><section><strong>{h}</strong><p>{p}</p></section></div>)}</aside></div></div></section>
 <section className="ng-section ng-tint"><div className="ng-wrap"><Intro eyebrow={t('ONE PERSON. A CLEAR START.','一个人，也可以有清晰的起点。')} title={t('Start with expertise, not a blank page.','从你的经验开始，不用从零想起。')}>{t('Here OPC means a one-person business supported by tools and collaborators. It describes how you operate, rather than a company registration type.','这里的 OPC 指由一个人主导、借助工具和合作伙伴经营的业务，是一种经营方式，并非特定的澳洲公司注册类型。')}</Intro><div className="ng-grid">{[[t('Professionals','有专业经验的人'),t('Package a skill into a review, research or advisory service.','把专业技能整理成诊断、研究或咨询服务。')],[t('Builders & creatives','开发者与创作者'),t('Offer a focused implementation or content package.','提供范围明确的搭建实施或内容套餐。')],[t('Independent operators','自由职业与副业探索者'),t('Make your offer easier to explain and deliver.','把服务讲清楚，让交付更容易执行。')]].map(([h,p])=><article className="ng-card" key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
 <section className="ng-section" ref={form} id="service-builder"><div className="ng-wrap ng-two"><div><Intro eyebrow={t('YOUR FIRST SERVICE','你的第一个服务')} title={t('Five answers. One clear plan.','回答 5 个问题，得到一份清晰方案。')}/><p>{t('Use everyday language. A focused problem is a better starting point than a long list of skills.','用日常语言描述即可。先解决一个具体问题，比列出一长串技能更容易开始。')}</p><button className="ng-button ng-secondary" onClick={example}>{t('Try an automation example','试填：AI 自动化服务')}</button><p className="ng-form-note">{t('This free tool uses structured templates in your browser. No AI API is connected. Your answers are not submitted or stored by this tool.','免费工具在浏览器内使用结构化模板生成草稿，目前未接入 AI API。工具不会提交或存储你的回答。')}</p></div><form className="ng-card ng-enquiry" onSubmit={generate}><label>1. {t('What can you help with?','你擅长什么？')}<input name="expertise" value={data.expertise} onChange={update} required maxLength={160} placeholder={t('e.g. research, design, workflow automation','例如：研究、设计、工作流程自动化')}/></label><label>2. {t('Who would you like to help?','你希望帮助谁？')}<input name="customer" value={data.customer} onChange={update} required maxLength={160} placeholder={t('e.g. small Australian service businesses','例如：澳洲小型服务企业')}/></label><label>3. {t('What specific problem will you solve?','你要解决什么具体问题？')}<input name="problem" value={data.problem} onChange={update} required maxLength={240} placeholder={t('e.g. time lost on enquiry follow-ups','例如：客户咨询和跟进占用太多时间')}/></label><label>4. {t('How would you deliver the service?','你希望以什么方式交付？')}<select name="format" value={data.format} onChange={update}>{Object.entries(formats).map(([v,f])=><option value={v} key={v}>{f[lang]}</option>)}</select></label><label>5. {t('Hours available each week','每周可以投入多少小时？')}<select name="hours" value={data.hours} onChange={update}>{['3–5','5–10','10–20','20+'].map(h=><option key={h}>{h}</option>)}</select></label><button type="submit" className="ng-button">{t('Generate my service plan ↗','生成我的服务方案 ↗')}</button><p className="ng-form-note">{t('A planning draft to test with customers. Review scope, pricing and any qualification requirements before selling.','这是一份用于客户验证的规划草稿。开展服务前，请确认范围、报价及所需资格。')}</p></form></div></section>
 {plan&&<section ref={result} tabIndex="-1" className="ng-section ng-tint opc-result" id="service-plan"><div className="ng-wrap"><Intro eyebrow={t('YOUR NEXT STEP STARTS HERE','从这一步开始行动')} title={t('Your service plan is ready. Make it yours.','你的服务方案已生成，继续把它变成你的。')}>{t('Edit the draft, save a copy, then validate it with a potential customer.','编辑草稿、保存一份，再与潜在客户验证。')}</Intro><label className="opc-draft-label" htmlFor="opc-draft">{t('Editable service plan','可编辑的服务方案')}</label><textarea id="opc-draft" className="opc-draft" value={draft} onChange={e=>setDraft(e.target.value)} rows={22}/><div className="ng-actions"><button className="ng-button" onClick={()=>copy(draft,t('Service plan copied.','服务方案已复制。'))}>{t('Copy plan','复制方案')}</button><button className="ng-button ng-secondary" onClick={download}>{t('Download .txt','下载文本')}</button><a className="ng-button ng-secondary" href={planEnquiry(draft,lang,source)}>{t('Discuss this plan with NextGenius ↗','和 NextGenius 讨论这份方案 ↗')}</a></div><p className="ng-form-note">{t('The enquiry link opens an email draft with this plan and the referral channel. Review it before sending.','咨询链接会打开邮件草稿，附上当前方案和来源渠道。请检查后自行发送。')}</p></div></section>}
 <section className="ng-section"><div className="ng-wrap"><Intro eyebrow={t('FROM AN IDEA TO A SERVICE','从想法走向服务')} title={t('Choose your next step.','选择你需要的下一步。')}/><div className="ng-grid">{[[t('Launch a service page','搭建服务页面'),t('Discuss a page for your offer, examples and enquiry flow.','讨论如何展示你的服务、示例成果及咨询入口。'),t('Discuss a service page ↗','咨询页面搭建 ↗'),'OPC service page'],[t('Make delivery easier','让交付更轻松'),t('Explore templates, enquiry handling and useful automation.','探索交付模板、客户咨询处理与实用自动化。'),t('Discuss delivery tools ↗','咨询交付工具 ↗'),'OPC delivery tools']].map(([h,p,b,interest])=><article key={h} className="ng-card"><h3>{h}</h3><p>{p}</p><a className="ng-button ng-secondary" href={planEnquiry((plan?draft+'\n\n':'')+interest,lang,source)}>{b}</a></article>)}<article className="ng-card"><h3>{t('Build with a network','连接互补的伙伴')}</h3><p>{t('Express interest in the emerging OPC network. Tell us what you offer and the help you need.','表达加入筹建中的 OPC 网络的意向，告诉我们你能提供什么、需要什么帮助。')}</p><Button to="/community" secondary>{t('Explore the network ↗','了解 OPC 网络 ↗')}</Button></article></div><p className="ng-form-note">{t('These are enquiry pathways. Service-page publishing, paid programmes and an automated member marketplace are not available in this tool.','以上为咨询入口。目前工具尚未提供服务页面自动发布、付费项目或自动化成员交易市场。')}</p></div></section>
 <section className="ng-section ng-tint"><div className="ng-wrap ng-two"><div><Intro eyebrow={t('PASS IT ON','分享给正在开始的人')} title={t('Know someone with skills to share?','身边有人正想开始独立经营？')}/><p>{t('Share the free tool. Choose the channel to copy a link in the current language.','分享这个免费工具。选择渠道，即可复制当前语言的专属链接。')}</p></div><div className="ng-card"><div className="ng-actions">{[['xiaohongshu','小红书'],['twitter','X / Twitter'],['linkedin','LinkedIn']].map(([s,label])=><button className="ng-button ng-secondary" key={s} onClick={()=>copy(campaignLink(lang,s),t(`${label} link copied.`,`${label} 链接已复制。`))}>{label}</button>)}</div><p className="ng-form-note">{t('Links identify the channel in a later enquiry draft; no analytics tracking has been added.','链接会在后续咨询草稿中注明来源渠道；目前未添加流量统计追踪。')}</p><Link to="/community">{t('Events, workshops & the OPC network ↗','活动、工作坊与 OPC 网络 ↗')}</Link></div></div></section><div className="opc-status" role="status" aria-live="polite">{status}</div></div></Layout>;
}
