export const formats = {
  review: {en:'Review & action plan',zh:'诊断与行动方案',steps:{en:['Collect the agreed inputs and confirm the customer’s priority.','Review the current process and identify practical improvements.','Deliver a findings summary and walk through the next steps.'],zh:['收集约定资料，确认客户最希望解决的问题。','梳理现有流程，识别可实施的改进。','交付诊断摘要与行动清单，并向客户说明下一步。']},price:{en:'A fixed fee per review, based on the inputs, depth and number of follow-up sessions.',zh:'按单次诊断收取固定费用；根据资料量、分析深度与跟进次数确定金额。'}},
  setup: {en:'Setup & implementation',zh:'搭建与实施',steps:{en:['Agree on one workflow, required access and an acceptance checklist.','Build a small pilot and test it with sample inputs.','Deliver the working setup, handover notes and an agreed support period.'],zh:['确定一个流程、必要权限与验收清单。','搭建小范围试用版本，用样本资料测试。','交付可用配置、操作说明及约定的支持期。']},price:{en:'A fixed project fee with milestones. Quote software costs and ongoing support separately.',zh:'采用项目固定报价与阶段付款；软件费用和后续维护单独列明。'}},
  content: {en:'Content & research package',zh:'内容与研究服务',steps:{en:['Agree on the audience, brief, sources and output format.','Produce a draft and check the supporting sources.','Deliver the reviewed package with one agreed revision round.'],zh:['确认受众、需求、资料来源与成果格式。','制作初稿并核对支撑资料。','交付审阅后的成果，包含一轮约定范围内的修改。']},price:{en:'A package fee for a defined number of outputs, or a monthly package after a successful pilot.',zh:'按明确数量的成果收取套餐费用；试单成功后再讨论月度服务。'}},
  coaching: {en:'Training & coaching',zh:'培训与辅导',steps:{en:['Assess the learner’s starting point and agree on one learning goal.','Run a practical session using a relevant example.','Provide exercises, a takeaway guide and an agreed follow-up.'],zh:['了解学员基础，明确一个学习目标。','结合相关案例开展实操课程。','提供练习、操作指南及约定的课后跟进。']},price:{en:'A fee per session or a short programme, based on preparation, session length and participant count.',zh:'按单次课程或短期辅导套餐报价，考虑准备时间、课时与参与人数。'}}
};
export function buildPlan(data,lang='en'){
 const zh=lang==='zh',f=formats[data.format]||formats.review;
 const expertise=data.expertise.trim(),customer=data.customer.trim(),problem=data.problem.trim();
 if(!expertise||!customer||!problem||!['3–5','5–10','10–20','20+'].includes(data.hours))throw new Error('Complete all five answers.');
 const title=zh?`${customer}｜${f.zh}`:`${f.en} for ${customer}`;
 const positioning=zh?`我运用${expertise}，帮助${customer}解决「${problem}」，从一项范围明确的${f.zh}开始。`:`I use ${expertise} to help ${customer} address “${problem}”, starting with a clearly scoped ${f.en.toLowerCase()}.`;
 const sections=zh?[
 ['服务定位',positioning],['首个服务套餐',`${title}\n先约定一个目标、交付期限、验收方式及修改次数。每周可投入 ${data.hours} 小时，先接一个试单，再根据实际工作量调整容量。`],['交付流程',f.steps.zh.map((s,i)=>`${i+1}. ${s}`).join('\n')],['报价结构',`${f.price.zh}\n先估算准备、交付、沟通与修改工时，再加上工具费用。金额需结合客户访谈与试单确定，本方案不提供市场价格估值。`],['AI 可以协助的环节','需求整理、资料摘要、初稿、检查清单与跟进草稿。对客户交付的内容由你审核；使用客户资料前，约定权限与工具使用范围。'],['第一周行动','1. 找 3 位目标客户了解问题与现有解决方式。\n2. 制作一份示例成果，验证交付时间。\n3. 写清服务范围、价格与验收标准。\n4. 邀请一位客户讨论小范围付费试单。'],['服务页面介绍',`${positioning}\n你将获得：约定范围内的交付成果、清晰的行动建议和必要的交接说明。\n欢迎联系我，先聊聊你的具体需求。`],['服务边界','范围外的工作另行报价；不承诺客户收入或业务结果。若涉及受监管服务，请在提供服务前核实所需资格与要求。']
 ]:[
 ['Positioning',positioning],['Your first package',`${title}\nAgree on one goal, a delivery date, acceptance criteria and revision limits. With ${data.hours} hours available each week, start with one pilot and adjust capacity using the actual workload.`],['Delivery workflow',f.steps.en.map((s,i)=>`${i+1}. ${s}`).join('\n')],['Pricing structure',`${f.price.en}\nEstimate preparation, delivery, communication and revision time, then add tool costs. Validate the amount through customer conversations and a pilot; this draft is not a market price estimate.`],['Where AI can help','Organise requirements, summarise inputs, prepare drafts, create checklists and draft follow-ups. Review everything you deliver. Agree on permissions and tool use before using customer data.'],['Your first week','1. Speak with 3 potential customers about the problem and current alternatives.\n2. Create a sample deliverable and measure the effort.\n3. Define scope, price and acceptance criteria.\n4. Invite one customer to discuss a small paid pilot.'],['Service page copy',`${positioning}\nYou receive: agreed deliverables, clear next steps and practical handover notes.\nGet in touch to discuss your specific needs.`],['Boundaries','Quote out-of-scope work separately. Do not promise customer revenue or business results. Check relevant qualifications and requirements before providing regulated services.']];
 return {title,text:[title,...sections.map(([h,t])=>`\n${h}\n${t}`)].join('\n'),positioning};
}
export function campaignLink(lang,source){return `${window.location.origin}/opc/?lang=${lang==='zh'?'zh':'en'}&source=${encodeURIComponent(source)}`;}
export function planEnquiry(text,lang,source){return 'mailto:info@nextgenius.com.au?subject='+encodeURIComponent(lang==='zh'?'OPC 服务搭建咨询':'OPC service launch enquiry')+'&body='+encodeURIComponent(`Source: ${source || 'website'}\n\n${text}\n\n${lang==='zh'?'我想获得的帮助：':'The help I am looking for:'}`);}
